import { SportEvent } from './types'

export const MOCK_EVENTS: SportEvent[] = [
  {
    id: 'evt-001',
    title: 'Большой футбольный фестиваль 2026',
    description:
      'Главное спортивное событие года для детей, тренеров и руководителей. 4 дня футбола, форумов и праздника для всей семьи. Турниры, мастер-классы, концерты и многое другое.',
    sport: 'football',
    date: '2026-08-04',
    endDate: '2026-08-07',
    location: 'Стадион Лужники',
    city: 'Москва',
    price: 500,
    totalTickets: 5000,
    soldTickets: 3820,
    imageUrl:
      'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    organizerId: 'org-001',
    organizerName: 'АФШ — Ассоциация футбольных школ',
    featured: true,
    tags: ['дети', 'тренеры', 'турнир', 'фестиваль'],
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'evt-002',
    title: 'Московский марафон 2026',
    description:
      'Ежегодный городской марафон через центральные улицы Москвы. Дистанции: 5 км, 10 км, полумарафон и марафон. Открыт для всех уровней подготовки.',
    sport: 'running',
    date: '2026-09-20',
    location: 'Красная площадь',
    city: 'Москва',
    price: 1200,
    totalTickets: 15000,
    soldTickets: 9500,
    imageUrl:
      'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&q=80',
    organizerId: 'org-002',
    organizerName: 'RunMoscow',
    featured: true,
    tags: ['марафон', 'бег', 'массовый старт'],
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'evt-003',
    title: 'Кубок России по баскетболу 3×3',
    description:
      'Уличный баскетбол 3 на 3 в центре Санкт-Петербурга. Командный зачёт, индивидуальные конкурсы и яркое шоу. Приходите поддержать любимые команды!',
    sport: 'basketball',
    date: '2026-07-15',
    location: 'Дворцовая площадь',
    city: 'Санкт-Петербург',
    price: 300,
    totalTickets: 3000,
    soldTickets: 2100,
    imageUrl:
      'https://images.unsplash.com/photo-1546519638405-a9c4ef0f4c8e?w=800&q=80',
    organizerId: 'org-003',
    organizerName: 'Федерация баскетбола России',
    featured: true,
    tags: ['баскетбол', '3x3', 'уличный'],
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'evt-004',
    title: 'Открытый турнир по теннису "Летний Кубок"',
    description:
      'Любительский теннисный турнир для всех возрастных групп. Категории: начинающие, любители, продвинутые. Призы и подарки от спонсоров.',
    sport: 'tennis',
    date: '2026-06-28',
    endDate: '2026-06-30',
    location: 'Теннисный клуб "Олимп"',
    city: 'Казань',
    price: 800,
    totalTickets: 200,
    soldTickets: 145,
    imageUrl:
      'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&q=80',
    organizerId: 'org-004',
    organizerName: 'ТК Олимп Казань',
    tags: ['теннис', 'любительский', 'кубок'],
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'evt-005',
    title: 'Чемпионат по плаванию "Невские волны"',
    description:
      'Городской чемпионат по плаванию в 50-метровом бассейне. Дистанции от 50 до 1500 метров, стили: вольный, брасс, спина, баттерфляй. Участие бесплатное.',
    sport: 'swimming',
    date: '2026-08-22',
    location: 'Дворец водных видов спорта',
    city: 'Санкт-Петербург',
    price: 0,
    totalTickets: 500,
    soldTickets: 380,
    imageUrl:
      'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=80',
    organizerId: 'org-005',
    organizerName: 'Федерация плавания СПб',
    tags: ['плавание', 'чемпионат', 'бесплатно'],
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'evt-006',
    title: 'Ночной хоккейный турнир',
    description:
      'Традиционный ночной хоккейный турнир среди любительских команд. Игры проходят с 22:00 до 6:00. Командный дух, азарт и незабываемая атмосфера!',
    sport: 'hockey',
    date: '2026-11-14',
    endDate: '2026-11-15',
    location: 'Ледовый дворец "Кристалл"',
    city: 'Екатеринбург',
    price: 2500,
    totalTickets: 400,
    soldTickets: 280,
    imageUrl:
      'https://images.unsplash.com/photo-1580234811497-9df7fd2f357e?w=800&q=80',
    organizerId: 'org-006',
    organizerName: 'ЛД Кристалл',
    tags: ['хоккей', 'ночной', 'любительский'],
    createdAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'evt-007',
    title: 'Фестиваль йоги "Гармония"',
    description:
      'Трёхдневный фестиваль йоги на природе. 40+ мастер-классов, медитации, лекции и вечерние практики. Все уровни приветствуются.',
    sport: 'yoga',
    date: '2026-07-03',
    endDate: '2026-07-05',
    location: 'Парк "Коломенское"',
    city: 'Москва',
    price: 1500,
    totalTickets: 800,
    soldTickets: 620,
    imageUrl:
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    organizerId: 'org-007',
    organizerName: 'Студия йоги "Пространство"',
    tags: ['йога', 'медитация', 'природа', 'фестиваль'],
    createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'evt-008',
    title: 'Бой вечера: Гала-шоу по боксу',
    description:
      'Профессиональные и любительские поединки. 8 боёв, VIP-ложи, фуршет. Вечер незабываемых эмоций и профессионального бокса на высшем уровне.',
    sport: 'boxing',
    date: '2026-10-03',
    location: 'Олимпийский',
    city: 'Москва',
    price: 2000,
    totalTickets: 6000,
    soldTickets: 4100,
    imageUrl:
      'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&q=80',
    organizerId: 'org-008',
    organizerName: 'Fight Night Productions',
    tags: ['бокс', 'гала', 'профессионалы'],
    createdAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'evt-009',
    title: 'Волейбольный турнир на пляже',
    description:
      'Пляжный волейбол на берегу Волги. Турнир среди пар, смешанные категории. Зрители входят бесплатно. Еда, музыка и море позитива!',
    sport: 'volleyball',
    date: '2026-07-25',
    endDate: '2026-07-26',
    location: 'Центральный пляж',
    city: 'Казань',
    price: 600,
    totalTickets: 64,
    soldTickets: 48,
    imageUrl:
      'https://images.unsplash.com/photo-1592656094267-764a45160876?w=800&q=80',
    organizerId: 'org-009',
    organizerName: 'Казанская федерация волейбола',
    tags: ['волейбол', 'пляж', 'пары'],
    createdAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'evt-010',
    title: 'Лыжная гонка "Уральский хребет"',
    description:
      'Классическая и коньковая лыжные гонки в горах Урала. Дистанции: 5, 15, 30 км. Профессиональная трасса, хронометраж, медали лучшим.',
    sport: 'skiing',
    date: '2027-02-14',
    endDate: '2027-02-15',
    location: 'Горнолыжный центр "Уктус"',
    city: 'Екатеринбург',
    price: 1000,
    totalTickets: 600,
    soldTickets: 320,
    imageUrl:
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    organizerId: 'org-010',
    organizerName: 'УрФО Лыжный союз',
    tags: ['лыжи', 'горы', 'гонка'],
    createdAt: '2026-05-20T10:00:00Z',
  },
]

export const CITIES = [
  'Москва',
  'Санкт-Петербург',
  'Казань',
  'Екатеринбург',
  'Новосибирск',
  'Краснодар',
  'Сочи',
  'Нижний Новгород',
]
